modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory
license="ARR" #mandatory
credits="Credit to the people" #optional
[[mods]] #mandatory
modId="expedite" #mandatory
version="1.18.1-0.1" #mandatory
displayName="Expedite" #mandatory
description='''
This mod adds new things to explore on your adventures and to refresh the progression
'''
[[dependencies.expedite]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "AFTER"
side = "BOTH"